using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.SqlClient;
using System.Data;

namespace FrbaHotel.Repositories
{
    public class DBConnection
    {
        static string _ConnectionString = @"Data Source=???;Initial Catalog=Empleados;User ID=sa;Password=???";

        public static string ConnectionString
        {
            get { return _ConnectionString; }
        }

        public static SqlCommand CrearComando()
        {
            string con = ConnectionString;
            SqlConnection _conexion = new SqlConnection();
            _conexion.ConnectionString = con;
            SqlCommand _comando = new SqlCommand();
            _comando = _conexion.CreateCommand();
            _comando.CommandType = CommandType.Text;
            return _comando;
        }

        public static SqlCommand CrearComandoStoredProcedure(string storedName)
        {
            string con = ConnectionString;
            SqlConnection _conexion = new SqlConnection(con);
            SqlCommand _comando = new SqlCommand(storedName, _conexion);
            _comando.CommandType = CommandType.StoredProcedure;
            return _comando;
        }

        public static int EjecutarComandoNonQuery(SqlCommand comando)
        {
            try
            {
                comando.Connection.Open();
                return comando.ExecuteNonQuery();
            }
            catch { throw; }
            finally
            {
                comando.Connection.Dispose();
                comando.Connection.Close();
            }
        }

        public static SqlDataReader EjecutarComandoSelect(SqlCommand comando)
        {
            SqlDataReader reader;
            try
            {
                comando.Connection.Open();
                reader = comando.ExecuteReader();
            }
            catch (Exception ex)
            { 
                throw ex; 
            }
            finally
            {
                comando.Connection.Close(); 
            }

            return reader;

            //Dejo esto comentado porque puede llegar a servir:

            /*DataTable _tabla = new DataTable();
            try
            {
                comando.Connection.Open();
                SqlDataAdapter adaptador = new SqlDataAdapter();
                adaptador.SelectCommand = comando;
                adaptador.Fill(_tabla);
            }
            catch (Exception ex)
            { throw ex; }
            finally
            { comando.Connection.Close(); }
            return _tabla;*/
        }


        public void conection()
        {
            //
            // First access the connection string.
            // ... This may be autogenerated in Visual Studio.
            //
            string connectionString = "hola";
            //
            // In a using statement, acquire the SqlConnection as a resource.
            //
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                //
                // Open the SqlConnection.
                //
                con.Open();
                //
                // The following code uses an SqlCommand based on the SqlConnection.
                //
                using (SqlCommand command = new SqlCommand("SELECT TOP 2 * FROM Dogs1", con))
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Console.WriteLine("{0} {1} {2}",
                        reader.GetInt32(0), reader.GetString(1), reader.GetString(2));
                    }
                }
            }
        }
    }
}
